### ISSUE TITLE
MATLAB execution not reliably stopped

### ISSUE THREAD

**Issue by bpalmintier** [GMLC-TDC/helics-runner#1]
Despite enclosing a matlab `exec` with `try, $MATLAB_EXEC, exit, catch, exit(-1), end`, MATLAB can still continue to run after successfully completing `$MATLAB_EXEC`

I noticed this running `FESTIV` on the Peregrine HPC where the final command in `FESTIV`: `disp('FESTIV has finished execution.')` is executed as seen in the log, but MATLAB continued to run forcing a manual job stop by `ssh` to `killall MATLAB`

**Comment by kdheepak** [comment]
MATLAB must have not returned an error code of `-1`. Do you know for certain that it has in this case? If MATLAB does not get to the `exit(-1)` expression, helics runner will not be able to stop the federation on account on this "failure", because helics runner does not know. My suggestion is to use `exit(-1)` everywhere when you know MATLAB has failed to proceed in an expected fashion. 

Additionally, I'll add a way to run a separate helics runner command to stop a running federation. It'll be part of the next release.

**Comment by bpalmintier** [comment]
In this case, Matlab finished it's execution normally rather than on an error, so the return code was and I think should be 0. But perhaps the issue is that al though it should have exited, MATLAB was still running even after the script ended. So likely something in how the command line was handled.

-Bryan

Sent from my iPhone. Apologies for typos.

On Sep 12, 2018, at 7:12 AM, Dheepak Krishnamurthy <notifications@github.com<mailto:notifications@github.com>> wrote:


MATLAB must have not returned an error code of -1. Do you know for certain that it has in this case? If MATLAB does not get to the exit(-1) expression, helics runner will not be able to stop the federation on account on this "failure", because helics runner does not know. My suggestion is to use exit(-1) everywhere when you know MATLAB has failed to proceed in an expected fashion.

Additionally, I'll add a way to run a separate helics runner command to stop a running federation. It'll be part of the next release.

**Comment by kdheepak** [comment]
If the error code was 0, then helics runner will not end the federation. It'll wait till all federates have completed and returned 0. If any federate fails, it'll kill the federation. So this "issue" was designed/expected behaviour. 

The related question is whether this behaviour should change. I don't think there can be a master federate because of the way HELICS works. I can however add in end time into the helics runner, so regardless of the status of the federation it'll kill it at a certain time. The runner does not kill anything elegantly, so I'm a little wary of going down this path. If this is a feature required that is currently not supported by the helics API my opinion is that we should open an issue in the main HELICS repository.

**Comment by kdheepak** [comment]
In the first comment you said you had to ssh and kill MATLAB. MATLAB couldn't have still been running after it returned the exit code `0`. Perhaps there was no error while running but MATLAB didn't exit? Maybe the helicsFederateFinalize or some other function hung? I've seen MATLAB hang when a thread is running in the background that hasn't been closed yet. Pinging @phlptp to see if he has any thoughts here.

**Comment by phlptp** [comment]
I have seen this a few times where there was a seg fault or other uncaught exception in the C++ code in the other thread, then some variables got lost and some of the underlying threads have hung then the code halts so it doesn't close out stuff.    Someday I want to put in timeouts and isolation detection so a federate would automatically terminate if it lost all contact, but building up to that will take a while.
